config/routes.rb
Rails.application.routes.draw do
root 'static_pages#home'
  
  resources :departments do
    resources :items
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items 
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :update, :edit, :destroy]

  def index
    @departments = Department.all 
  end

  def show
    
  end

  def new
    @department = Department.new
    render partial: "form" 
  end

  def edit
    render partial: "form" 
  end

  def update
    if @department.update(department_params) 
      redirect_to department_path(@department.id)
    else 
      render :edit 
    end 
  end 

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else 
      render :new 
    end 
  end

  def destroy
    @department.destory 
    redirect_to departments_path
  end

  private
  def department_params
    params.require(:department).permit(:name, :email, :number)
  end

  def set_department 
    @department = Department.find(params[:id]) 
  end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item , only: [:show, :edit, :update, :destroy]
  def index
    @items = @department.items 
  end

  def show

  end

  def new
    @item = Item.new 
    render partial: "form" 
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_item_path(@department, @item)
    else 
      render :new 
    end 
  end 

  def edit
    render partial: "form"
  end

  def update
    
    if @item.update(item_params)
      redirect_to department_item_path(@department, @item)
    else 
      render :edit 
    end 
  end 

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)
  end 

  private 

  def item_params
    params.require(:item).permit(:name, :price)
  end

  def set_department 
    @department = Department.find(params[:department_id])
  end 

  def set_item
    @item = Item.find(params[:id])
  end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? 'Edit Department' : 'Create Department' %></h1>
<%= form_for @department do |d| %>
  <%= d.label :name %>
  <%= d.text_field :name %>
  <br /> 
  <%= d.label :email %>
  <%= d.text_field :email %>
  <br /> 
  <%= d.label :number %>
  <%= d.text_field :number %>
  <br /> 
  <%= d.submit %>
  <% end %>
 

app/views/departments/index.html.erb
<div class="container text-center"><h1>Departments</h1></div>
<hr /> 
<div class="container text-center"> 
<%= link_to "Create a new Department", new_department_path %>
</div>

<ul class="list-inline">
<% @departments.each do |department| %>
  <li class="list-inline-item"><%= link_to department.name, department_path(department) %></li>
<% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1> 
<ul>
  <li>Email: <%= @department.email %></li>
  <li>Phone: <%= @department.number %></li>
</ul>
<button><%= link_to 'Delete Department', @department, method: :delete %></button>
<button><%= link_to 'Edit Department', edit_department_path(@department) %></button>
<button><%= link_to 'Back To Departments', departments_path %></button>
<hr />
<h3>Please look at my items</h3>
<button><%= link_to "See items", department_items_path(@department)%></button>


 

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Department' : 'Create Department' %></h1>
<%= form_for [@department, @item] do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>
  <br /> 
  <%= t.label :price %>
  <%= t.text_field :price %>
  <br /> 
  <%= t.submit %>
  <% end %> 

app/views/items/index.html.erb
<div class="container text-center"><h1> Items </h1></div>
<hr /> 
<p>See more details by clicking</p> 
<button><%= link_to "Add Item", new_department_item_path(@department) %> </button>
<ul>
<% @items.each do |item| %>
  <li class="list-inline-item"><%= link_to item.name, [@department, item] %></li>
<% end %>
</ul> 
<<button><%= link_to "Back to Department", department_path(@department) %> </button>

app/views/items/show.html.erb
<h1><%= @department.name %></h1>
<h5>Name: <%= @item.name %></h5>
<ul>
  <li>Price: <%= @item.price %>$</li>
</ul>
<button><%= link_to 'Edit item', edit_department_item_path([@department, @item]) %></button>
<button><%= link_to 'Delete item', [@department, @item], method: :delete %></button>
<button><%= link_to 'Back To Items', department_items_path(@department) %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="container text-center border border-success">
<iframe src="https://giphy.com/embed/1cXN3ppw2lC0M" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
<p class="text-danger">Enter the legit department store</p>
<button type="button" class="btn btn-success" ><%= link_to "Enter", departments_path %></button>
</div>